### ISSUE TITLE
ECS: Remove systems needing a direct reference to another system for scheduling.

### ISSUE THREAD

**Issue by christopher-buss** [AetherInteractiveLtd/Tina#44]
Currently, the system `after` table takes a reference to another system. For this reason, systems must be stored as singleton objects rather than as a class that we can create a new instance of. If we only choose to use one world, this is not an issue! But if there is a desire for multiple worlds, we may want the ability to reuse systems such as for a character controller between different worlds - currently this is not possible.

We need to investigate how we can set this up better. One option is to instead provide the name of a system rather than the system itself, although I believe this could lead to other issues down the road, if for example the system was renamed and the user did not realise. The system currently does not necessarily need a name provided either, so this is another point of contention.

**Comment by RigidStudios** [comment]
We probably should give Systems names for Debug purposes (though slightly unnecessary), but I'm quite opposed to them being used as static symbols (in which you could make typos).

Can we instead include an Enum somewhere with execution point alphas, then you just sort the systems whenever you get a new system in order of their requested execution?

**Comment by christopher-buss** [comment]
System names should probably be pulled from `debug.info` anyway - if this is possible, rather than having to define them.
